### ISSUE TITLE
Ubuntu 21.04, just displays Error

### ISSUE THREAD

**Issue by madorian** [daniellandau/switcher#146]
Is it supposed to work on 21.04?

I found rofi, though, which works for me: 
https://github.com/davatorium/rofi

**Comment by paven** [comment]
Works for me on Ubuntu 20.04. But settings page get the following:

_The settings of extension switcher@landau.fi had an error:
```
TypeError: Gtk.StyleContext.add_provider_for_display is not a function
```

Stack trace:
```
buildPrefsWidget@/home/pvn/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:25:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```_

Is it the same error?
